### ISSUE TITLE
ImportError handling

### ISSUE THREAD

**Issue by Goldziher** [ariebovenberg/slotscheck#103]
Hi there,

So I encountered a problem that currently forced me to disable this tool in pre-commit. You can see the pertinent branch here: https://github.com/starlite-api/starlite/pull/315

The issue is that this plugin fails on import errors. In the above linked branch we are creating rust based extension and we are using a *.pyi file for its typings. Import fails because the extension is not built during pre-commit. 

I'd like to suggest one of the following to handle this: stop failing on import errors. Maybe make this configurable with a command line arg, e.g. emit error, warning or continue on import error, but in any case the preferable opinion from my PoV is to to skip import errors and continue without failure.

**Comment by ariebovenberg** [comment]
@Goldziher thanks for posting. Just a quick check: `--no-strict-imports` doesn't do the trick?

**Comment by Goldziher** [comment]
> @Goldziher thanks for posting. Just a quick check: does `--no-strict-imports` work for your case?

It does. Silly me 😁
