### ISSUE TITLE
Allow running `python -m slotscheck`

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/slotscheck#13]
Suggested on Reddit by /u/Rawing7 to add `__main__.py` enabling this behavior.

**Comment by ariebovenberg** [comment]
Added in v0.2, which was just published.

**Comment by sondrelg** [comment]
Nice! To make it run with pre-commit I think you now only need a `.pre-commit-hooks.yaml` (see [this](https://github.com/snok/pep585-upgrade/blob/master/.pre-commit-hooks.yaml) example) 🙂

**Comment by ariebovenberg** [comment]
@sondrelg I created a separate issue so we don't forget to add this #17
