### ISSUE TITLE
Python 3.12 and generics

### ISSUE THREAD

**Issue by dantownsend** [ariebovenberg/slotscheck#201]
We use `slotscheck` in the CI for Piccolo and sister projects.

For Python 3.12, they changed `Generic` - it no longer defines `__slots__`.

This means code like this now fails slotscheck:

https://github.com/piccolo-orm/piccolo/blob/febe5bbdc76cbcba50a994187cf9d953d52a00d3/piccolo/engine/base.py#L27

I know there's a new syntax for defining generics in Python 3.12, but as Piccolo supports Python 3.8 and above, it's harder to implement.

Any ideas how we can fix this? Maybe a special case for `Generic` in slotscheck (I haven't checked whether using `Generic` does invalidate the slots in child classes, but I assume not).

Thanks!

**Comment by ariebovenberg** [comment]
Hi @dantownsend, thanks for opening this issue. I'm having a look at this today

**Comment by ariebovenberg** [comment]
Looks like `Generic` was moved to an extension module, and didn't define `__slots__` anymore. A special case needed to be added.

**Comment by dantownsend** [comment]
@ariebovenberg Yeah, that's my understanding too. Thanks a lot for looking into it so quickly 👍

**Comment by ariebovenberg** [comment]
version 0.17.1 is now out on PyPI with the fix 🔧

**Comment by dantownsend** [comment]
@ariebovenberg Awesome, thanks a lot! 🎉🎉🎉
