### ISSUE TITLE
Add pre-commit config

### ISSUE THREAD

**Issue by Goldziher** [ariebovenberg/slotscheck#45]
Hi there,

Thanks for this useful library. I am integrating it in the starlite pipeline (https://github.com/starlite-api/starlite).

Would be awesome if I could run this as part of pre-commit. For this you will need to add a pre-commit config to the library - its not hard and will increase exposure i think. 

best

**Comment by ariebovenberg** [comment]
Hi @Goldziher, thanks for reaching out!

I've recently added a pre-commit setup, see [here](https://slotscheck.readthedocs.io/en/latest/advanced.html#pre-commit-hook). I must admit I'm not that familiar with pre-commit, so let me know if something isn't clear or is incorrect.

**Comment by Goldziher** [comment]
Great stuff, it works nicely for me:

```yaml
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.9.0
    hooks:
      - id: slotscheck
        exclude: "^(?!starlite/)"
        additional_dependencies:
          [
            openapi_schema_pydantic,
            orjson,
            pydantic,
            pydantic_factories,
            pyyaml,
            starlette,
            sqlalchemy,
            requests,
            jinja2,
            mako,
          ]
```

Probably a good idea to note in the docs that the user will need to specify any dependencies imported into the code, or the slotscheck will fail with stuff like this:

```sh
    from starlite.response import Response
  File "/Users/naamanhirschfeld/workspace/starlite/starlite/response.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Mind you - my code doesn't extend the yaml classes etc. But pre-commit creates its own encapsulated virtual-env, and these dependencies don't exist in it. MyPy for example handles this by suppressing this kind of error, but pylint - as a counter example, does not. 

Please close the issue when ready.

**Comment by ariebovenberg** [comment]
@Goldziher interesting! What makes this complicated is that `slotscheck` needs to import/run the code. Any requirements of the code will need to be repeated for this separate virtualenv. Not ideal.

`language: system` seems like a good solution _to me_ 🤔 . It can re-use the currently active environment (`slotscheck` will have to be installed of course). No `additional_dependencies` required, plus it works for scanning a library which is installed in editable mode.

Is there anything I'm missing about this option? I can imagine it wouldn't work for everyone — although they can always override with `language: python` and `additional_dependencies` if they like

**Comment by Goldziher** [comment]
It depends on how you run it. I run pre-commit in CI. I also don't like to have this stuff in dev dependencies.  But Yhea its viable.

**Comment by ariebovenberg** [comment]
@Goldziher good to know that there is probably demand for both options. I'll add a note about this in the docs.

**Comment by ariebovenberg** [comment]
I've added a detailed description about dependency management approaches to the pre-commit docs as of v0.10.0: https://slotscheck.readthedocs.io/en/latest/advanced.html#pre-commit-hook
