### ISSUE TITLE
Setup.cfg support?

### ISSUE THREAD

**Issue by q0w** [ariebovenberg/slotscheck#52]
Would you mind adding setup.cfg support for the configuration?

**Comment by ariebovenberg** [comment]
The reason it's not currently supported is that `pyproject.toml` seems to be the standard nowadays.

However...having read some of the [opinions](https://github.com/psf/black/issues/683) on `black`, I think it'd be reasonable for slotscheck to support `setup.cfg` as well.

Note you can currently use `--settings slotscheck.toml` if you want to avoid using `pyproject.toml` specifically

**Comment by q0w** [comment]
1. Yes.
2. Yes.
3. Flake8 instead [checks parent directories](https://github.com/PyCQA/flake8/blob/ca573a7ccf2d4a1c7df0b577bb6d3455c941e828/src/flake8/options/config.py#L17). Maybe should check subdirectories.
4. Raise exc if the specified file does not exist [like in flake8](https://github.com/PyCQA/flake8/blob/ca573a7ccf2d4a1c7df0b577bb6d3455c941e828/src/flake8/options/config.py#L64), maybe ValueError.

I started implementing this feature, but not sure to bring it to a close.

**Comment by ariebovenberg** [comment]
I don't mind handling the final stretch. Let me know when you have something.

**Comment by ariebovenberg** [comment]
This is supported as of version 0.12.0
