### ISSUE TITLE
Checks fail for classes with immutable metaclasses

### ISSUE THREAD

**Issue by shiftinv** [ariebovenberg/slotscheck#65]
First of all, thank you for this neat tool!

I've been seeing issues with checking classes that have immutable metaclasses, or generally metaclasses that raise an exception in their `__setattr__` (or `__delattr__`), due to this:
https://github.com/ariebovenberg/slotscheck/blob/9a2cba3fcdaab52bbc1d7d22e1c6689096a93e61/src/slotscheck/checks.py#L74

This seems to be the case defined in the tests here:
https://github.com/ariebovenberg/slotscheck/blob/9a2cba3fcdaab52bbc1d7d22e1c6689096a93e61/tests/src/test_checks.py#L41-L47

I'm not too familiar with the specifics of Python extensions, so I couldn't come up with any good solutions, but it would be nice if these types were supported as well.

*edit:* the second half of [this](https://stackoverflow.com/a/41012823/5080607) answer may be useful? Seems like an implementation quirk though, so it would need some testing to make sure it's reliable :/

**Comment by ariebovenberg** [comment]
@shiftinv many thanks for this find! The answer in the link not be 100% provably correct, but it's way better than the current check.

related: #8 

In any case: I can implement this rather easily.

**Comment by shiftinv** [comment]
Awesome, thank you for the quick fix!
