### ISSUE TITLE
`is_pure_python` edge cases in CPython 3.10

### ISSUE THREAD

**Issue by shiftinv** [ariebovenberg/slotscheck#92]
Hiya,
it appears that CPython's behavior slightly changed in 3.10 with `Py_TPFLAGS_HEAPTYPE` now also being set on `array.array` despite being implemented in an extension module, which unfortunately somewhat breaks the solution proposed in #65:

```sh
$ cat test.py
import array

class CustomArray(array.array):
    __slots__ = ()

$ python3.8 -m slotscheck test.py
All OK!
Scanned 1 module(s), 1 class(es).

$ python3.10 -m slotscheck test.py
ERROR: 'test:CustomArray' has slots but superclass does not.
Oh no, found some problems!
Scanned 1 module(s), 1 class(es).

$ python3.8 -c 'import array; print(bin(array.array.__flags__))'
0b1000001010000000000

$ python3.10 -c 'import array; print(bin(array.array.__flags__))'
0b101011100100000  ### Py_TPFLAGS_HEAPTYPE (1<<9) is now set 
```

As far as I can tell, possible solutions would be:
- removing the cpython-specific check, since the implementation-agnostic check appears to work, at least for this particular instance - not sure about the edge cases there though :thinking: 
- or checking whether `Py_TPFLAGS_IMMUTABLETYPE (1<<8)` is *not* set instead of checking if `Py_TPFLAGS_HEAPTYPE (1<<9)` is set; perhaps checking both to keep compatibility with < 3.10

`Py_TPFLAGS_IMMUTABLETYPE` got added in 3.10 and appears to be intended as a replacement for `Py_TPFLAGS_HEAPTYPE` judging by these pages:
- https://github.com/python/cpython/pull/25816/files
- https://docs.python.org/3.10/c-api/typeobj.html#Py_TPFLAGS_IMMUTABLETYPE
- https://github.com/python/cpython/pull/25520/files#diff-1decebeef15f4e0b0ce106c665751ec55068d4d1d1825847925ad4f528b5b872

**Comment by ariebovenberg** [comment]
@shiftinv thanks for posting! Using `Py_TPFLAGS_IMMUTABLETYPE` seems like the way to go here. In the end we aren't actually interested if something is defined in an extension module -- we just want to have a good guess whether it has slots. Immutable types _most likely_ have slots, as do extension classes. Note that `Exception` is the exception 😄
